### ISSUE TITLE
Multiple sounds playing at the same time

### ISSUE THREAD

**Issue by pazooki** [yuma-m/synthesizer#9]
First of all great job making this lib. I want to know how to combine two or more sounds to play simultaneously?

**Comment by yuma-m** [comment]
Hi @pazooki, Does this sample work for you?
https://github.com/yuma-m/synthesizer/blob/master/example/play_chord.py

**Comment by pazooki** [comment]
I figured that I can do this:
```python
sound = self.synthesizer.generate_constant_wave(450.0, duration)
sound *= self.synthesizer.generate_constant_wave(750.0, duration)
```
